### ISSUE TITLE
The version of antlr4-python3-runtime on pypi is the python 2 version

### ISSUE THREAD

**Issue by DRMacIver** [antlr/antlr4-python3#14]
And as a result doesn't actually work on python 3.

To reproduce:

Download the tar.gz from pypi (You can install it with pip but I wanted to make sure that pip wasn't confused)

Unpack it

in the src directory run e.g. 

    python3.4 -m antlr4.atn.Transition

You'll get:

    /usr/local/bin/python3.4: Error while finding spec for 'antlr4.atn.Transition' (<class 'ImportError'>: No module named '__builtin__')

The reason for this being the following line in that file right at the top:

    from __builtin__ import unicode

This isn't python 3 code, it's python 2. If you look in the same file in this repo (https://github.com/antlr/antlr4-python3/blob/master/src/antlr4/atn/Transition.py) there's no similar problem. I think you've somehow accidentally shipped the python 2 runtime as the python 3 one.

**Comment by DRMacIver** [comment]
Somewhat relatedly, why are you doing it this way at all? Having separate packages for the python 2 and python 3 versions is just weird and makes adding a dependency on antlr pretty awkward. As far as I can tell all you're getting out of it are the ability to add non-functioning type annotations in this repo and a relatively small set of differences that would be easy to paper over using [six](https://pypi.python.org/pypi/six), and at the cost of a very unusual packaging setup and a lot of manual work to keep the two in sync.

**Comment by ericvergnaud** [comment]
mmm...
just manually downloaded the runtime from PyPI and the __init__.py at the root of atn only contains __author__='ericvergnaud'
Seems to me that the issue comes from your installation pointing to the antlr2 version.

**Comment by DRMacIver** [comment]
I am almost 100% sure that's not the case. That's why I described manually downloading the package from pypi so as to make sure that was not what was happening. 

To be concrete:

   1. Go to https://pypi.python.org/pypi/antlr4-python3-runtime
   2. Click the download button. This goes to https://pypi.python.org/packages/source/a/antlr4-python3-runtime/antlr4-python3-runtime-4.5.tar.gz
   3. Now observe the following test:

    $ tar -xvf antlr4-python3-runtime-4.5.tar.gz ^C
    $ cd antlr4-python3-runtime-4.5/
    $ grep -R __builtin__ .

     ./src/antlr4/Recognizer.py:from __builtin__ import unicode
     ./src/antlr4/atn/Transition.py:from __builtin__ import unicode

As you see, this has the \_\_builtin\_\_ problem I reported.

To demonstrate that this is breaking under python3.4 as expected:

    $ PYTHONPATH=. python3.4 ./antlr4/atn/Transition.py 

    Traceback (most recent call last):
    File "./antlr4/atn/Transition.py", line 44, in <module>
    from __builtin__ import unicode
    ImportError: No module named '__builtin__'

**Comment by DRMacIver** [comment]
In fact to more easily demonstrate it, this is what's in the setup.py of that archive when unpacked:

    setup(
        name='antlr4-python2-runtime',
        version='4.5',
        packages=['antlr4', 'antlr4.atn', 'antlr4.dfa', 'antlr4.tree', 'antlr4.error', 'antlr4.xpath'],
        package_dir={'': 'src'},
        url='http://www.antlr.org',
        license='BSD',
        author='Eric Vergnaud, Terence Parr, Sam Harwell',
        author_email='eric.vergnaud@wanadoo.fr',
        description='ANTLR 4.5 runtime for Python 2.7.6'
    )

**Comment by ericvergnaud** [comment]
Ok should be fixed now, can you retry?

**Comment by DRMacIver** [comment]
Apologies, I had to step out. I'll be back at my computer in an hour or two
and will try then.

**Comment by ericvergnaud** [comment]
Ok I leave that open for now.
Thanks for your feedback.
Re the 2/3 subject, in essence this can be rephrased into 'why have 2 incompatible versions of Python ?'. In short, you need to complain to GVR, not to me.

**Comment by DRMacIver** [comment]
No, not really. There are pretty well established ways of having a single
version of the library that works on both python 2 and python 3. Having
separate packages for the two different versions is pretty unusual.

**Comment by ericvergnaud** [comment]
Well maybe I’m setting new standards then!

**Comment by DRMacIver** [comment]
Well the approach of having two nearly identical code bases that you have to manually keep in sync isn't exactly an improvement on the status quo of using \_\_future\_\_ imports and depending on a small shim library to write code that runs fine on both.

I'd be happy to submit a pull request that either makes this repo python 2 compatible or the other one python 3 compatible if you'd like? I've had a quick look and I don't see any major obstacles, though I could be missing something.

At any rate, the issue of the python 3 version on pypi being the wrong one is fixed so I'll close this now.

**Comment by ericvergnaud** [comment]
Hi, 

thanks but that’s not our strategy.

We believe that as Python 3 usage grows, having to maintain backwards compatibility with Python 2 will be a source of problems.
We also do not want to depend on a 3rd party library, which would force users to use the same version as ours.
The maintenance is really not an issue. The difficult part is to identify the bug and the fix, not to copy it to the other code base.

Having said that, you are welcome to propose a python-six target, if you find it useful and are willing to maintain it (I won’t).

Cheers,

Eric

**Comment by DRMacIver** [comment]
OK. Your strategy is entirely wrong-headed, but I don't really see much use in arguing the point. Good luck with it.

**Comment by ericvergnaud** [comment]
It’s really a pleasure to work for free for an open source community of nice and open minded people filled with humility and always keen to help rather than complain and criticize.

**Comment by DRMacIver** [comment]
\*shrug\*. I was evaluating whether or not to use your software as a dependency for the open source library that I also work for for free. In the course of doing so I found that it had been completely broken for two weeks for reasons that only can exist because you're doing something entirely unnecessary and vastly more complicated than the way literally anyone who takes this seriously does it. I politely pointed this out and offered to help you fix it only to be told you like it this way. Do you see how maybe this looks like it's not worth my time?

I mean, I do appreciate the work. ANTLR appears to be nice software and I'm glad you think it's worth the effort to support python, but you've signalled "this is not safe to depend on and will cause your users grief, and we're not prepared to fix that" so hard that what exactly is it you think I am I supposed to do?

**Comment by ericvergnaud** [comment]
As already suggested, your tone is inappropriate.

**Comment by DRMacIver** [comment]
As already suggested, I'm done here.
