### ISSUE TITLE
Annotated parameter problem at __init__

### ISSUE THREAD

**Issue by niuniu4** [antlr/antlr4-python3#23]
When trying to pass parameter to rule, if you do not specify the type like this
row[columns] returns [values]
the generated context class will looks like 
def __init__ (..... , columns:=None)  <<Syntax error at ':'. Python does not necessary have to specify the type.

but if you do things like
row[list columns] returns [values]
there is also runtime error cause the generated code looks like 
def __init__ (..... , columns:list=None) 
columns can not be initialized as None cause NoneType can not assign to list type.

to resolve the headache, I have use object as the type but it looks ugly. Maybe this can be fixed easily remove all these type annotations.

And it might also better to add type annotation to the 'ctx' parameter in base listener/visitor, so when edit in the IDE like PyCharm, so it can find out the method/attribute name.

**Comment by ericvergnaud** [comment]
#7b0f194 fixes the extra colon only, please file separate issues for list and missing type annotations
