### ISSUE TITLE
'grun' python version

### ISSUE THREAD

**Issue by jszheng** [antlr/antlr4-python3#26]
Not a bug.
grun is useful while reading the book. just spend some time write a py3 version, maybe helpful to others.
https://github.com/jszheng/pygrun

**Comment by ericvergnaud** [comment]
Hi,

great!
Maybe developers will find it easier to grab this from the antlr repo.

Eric

**Comment by jszheng** [comment]
Sure. Feel free to modify and move to anywhere that reasonable. I put it here cause It tied up with the runtime and directly used internal data structure.

**Comment by ericvergnaud** [comment]
Hi,
please sign the contributors agreement, and submit a PR.
Welcome.
Eric

**Comment by parrt** [comment]
https://github.com/antlr/antlr4/blob/master/contributors.txt

**Comment by parrt** [comment]
excellent. Added to the repository py3

https://github.com/antlr/antlr4-python3/tree/master/bin

Ter

On Sun, Apr 26, 2015 at 6:15 PM, jszheng <notifications@github.com> wrote:

> Sure. Feel free to modify and move to anywhere that reasonable. I put it
> here cause It tied up with the runtime and directly used internal data
> structure.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/antlr/antlr4-python3/issues/26#issuecomment-96456363>.
>



-- 
Dictation in use. Please excuse homophones, malapropisms, and nonsense.

**Comment by ericvergnaud** [comment]
Do i need to do something, or can I close this?

**Comment by ericvergnaud** [comment]
No feed back, so closing
