### ISSUE TITLE
re-write the book example in python

### ISSUE THREAD

**Issue by jszheng** [antlr/antlr4-python3#28]
I have tried to rewrite the example from java to python3, some of them is now here
https://github.com/jszheng/py3antlr4book
Most of them may just easy but something in JAVA runtime does not exist in py runtime yet. So some example may probe into source code that may not be good style.
ex. 
TokenStreamRewrite is implemented https://github.com/jszheng/py3antlr4book/tree/master/12-channel

and also to parse with inline action for a large file, there is no un-buffered stream, even without build AST tree, read all file in memory may not possible.
https://github.com/jszheng/py3antlr4book/blob/master/10-calc
seems like a workaround.

Hope this might help.

**Comment by ericvergnaud** [comment]
Hi,
it does help, but this information would be more useful on the google group than as an open issue.
Eric
