### ISSUE TITLE
`java-escape` written instead of the grammar file name

### ISSUE THREAD

**Issue by jcbrinfo** [antlr/antlr4-python3#39]
ANTLR puts the folowing comment on top of every Python file it generates, regardless of the actual name of the grammar:

```
# Generated from java-escape by ANTLR 4.5
```

Futhermore, in the class definition of the parser, the `grammarFileName` attribute is always set to `"java-escape"`. The occurrences of the `java-escape` string seem to be generated by lines [130](https://github.com/antlr/antlr4-python3/blob/master/tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg#L130) and [146](https://github.com/antlr/antlr4-python3/blob/master/tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg#L146) of the template, but I do not known StringTemplate enough to propose a fix.

**Comment by sharwell** [comment]
Assuming Python doesn't treat `\` characters in a special way within comments (Java does), you can just do this:

| Before | After |
| --- | --- |
| `<grammarFileName; format="java-escape">` | `<grammarFileName>` |
| `<parser.grammarFileName; format="java-escape">` | `<parser.grammarFileName>` |

**Comment by ericvergnaud** [comment]
Why does the java generator need this format? The grammarFileName cannot contain escaped characters, can it?

**Comment by sharwell** [comment]
@ericvergnaud An example is shown in antlr/antlr4#164. It's a rare occurrence, but highly disruptive when it appears. When I first hit it, I was working on a project in collaboration with [UIUC](http://illinois.edu/). They use the top-level package **edu.uiuc**, which caused the issue to affect most of their builds. :laughing:

**Comment by ericvergnaud** [comment]
Not 100% sure (haven't tried it) but from the specs I believe Python comments also support unicode escapes.
Why is it that format="java-escape" is understood by ST when generating Java target and not when generating other targets?

**Comment by ericvergnaud** [comment]
Ok found it -> JavaStringRenderer

**Comment by sharwell** [comment]
Based on [this answer](http://stackoverflow.com/a/28908989/138304), the escape sequences wouldn't cause a problem for Python. Currently the format is restricted to Java (language and code generation templates) because it's the only supported language I was aware of that behaved in this manner. Obviously if other targets are affected it would make sense to expand the support.

**Comment by jcbrinfo** [comment]
If I understand correctly, only the half of the problem is solved. The first case is effectively a comment. But, the second case is a string literal, so the path has to be escaped.

**Comment by sharwell** [comment]
:worried: Yes, sounds like we'll need a `PythonStringRenderer` and `python-escape` to handle this.

**Comment by sharwell** [comment]
For a general solution, I would suggest something like the [`string`](https://github.com/antlr/antlr4/blob/master/tool/test/org/antlr/v4/test/runtime/java/Java.test.stg#L114-L116) or [`writeStringLiteral`](https://github.com/antlr/antlr4/blob/master/tool/test/org/antlr/v4/test/runtime/java/Java.test.stg#L126-L141) template, backed by a tool-injected `Map` that knows how to escape strings in a target language. This would be a separate issue for discussion though in antlr/antlr4.

:memo: The difference between `string` and `writeStringLiteral` comes from the way they render multi-line string literals.

**Comment by sharwell** [comment]
@jcbrinfo Maybe create a new issue for the instance which was creating a string literal in the output, since this one was geared specifically towards the header. I had assumed we were dealing specifically with comments and missed that the two cases were very different. :worried:

**Comment by jcbrinfo** [comment]
In fact, paths can technically include any characters, except NULL. So, putting a raw path is dangerous (in theory) even inside a Python comment. But, in practice, I do not know anybody that is crazy enough to put an `LF` in a filename... :smile:
