### ISSUE TITLE
ANTLR4/Python target is much slower than ANTLR4/Java with C.g4

### ISSUE THREAD

**Issue by ilyaigpetrov** [antlr/antlr4-python3#44]
Hi, guys.

I took C language grammar `C.g4` [ https://github.com/antlr/grammars-v4/blob/master/c/C.g4 ] and encountered some performance problem with it and `Python3` target.
Here are cygwin logs that demonstrate the problem:
```console
$ antlr4 -Dlanguage=Python3 C.g4
$ cat Out.c
typedef Py_ssize_t Py_ssize_clean_t;
void AnnotateRWLockCreate(const char *file, int line, const volatile void *lock);
$ time pygrun.bat C compilationUnit Out.c -d
line 1:35 reportAttemptingFullContext d=32 (declarationSpecifiers), input='Py_ssize_clean_t;'
line 1:35 reportAmbiguity d=32 (declarationSpecifiers): ambigAlts={1, 2}, input='Py_ssize_clean_t;'
line 2:52 reportAttemptingFullContext d=84 (parameterDeclaration), input='intline,'
line 2:52 reportAmbiguity d=84 (parameterDeclaration): ambigAlts={1, 2}, input='intline,'

real    0m16.485s
user    0m0.000s
sys     0m0.046s

$ antlr4 C.g4 && javac C*.java
$ time grun C compilationUnit Out.c -diagnostics
line 1:35 reportAttemptingFullContext d=32 (declarationSpecifiers), input='Py_ssize_clean_t;'
line 1:35 reportAmbiguity d=32 (declarationSpecifiers): ambigAlts={1, 2}, input='Py_ssize_clean_t;'
line 2:52 reportAttemptingFullContext d=84 (parameterDeclaration), input='intline,'
line 2:52 reportAmbiguity d=84 (parameterDeclaration): ambigAlts={1, 2}, input='intline,'

real    0m0.791s
user    0m0.015s
sys     0m0.030s
```
So the difference is enormous. I have larger real world input files which Java handles and Python3 fails to handle (just chokes on them). I've also tried Python2 target with the same result.
The problem is not crucial for me as yet I can stick to Java target but I wanted you to know about the problem.

Thanks for your great tool.

**Comment by parrt** [comment]
The C grammar is not optimzed and will be slow for any language target compared to our Java grammar. but thanks for report.
Ter

**Comment by ericvergnaud** [comment]
Hi,

I am sure that you are aware that Python is 20-30 times slower than  Java.
See: http://benchmarksgame.alioth.debian.org/u64q/python.html <http://benchmarksgame.alioth.debian.org/u64q/python.html>
You can’t expect antlr to perform better

Eric
